name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Gradle
      run: sudo apt-get -y -qq update && sudo apt-get -y -qq install gradle

    - name: Create application.yaml
      run: echo "${{ secrets.APPLICATION.YAML }}" > ./src/main/resources/application.yaml

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: cd ./ && ./gradlew clean build

    - name: Make zip file
      run: zip -r ./short-url.zip .
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload to S3
      run: aws s3 cp --region ${{ secrets.AWS_REGION }} ./short-url.zip s3://short-url/short-url.zip

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name short-url-deploy \
        --deployment-group-name short-url-sever \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=short-url,bundleType=zip,key=short-url.zip \
        --region ${{ secrets.AWS_REGION }}
